language: java

os:
  - linux
jdk:
  - openjdk8
addons:
  apt:
    packages:
    - openjdk-8-jdk-headless
    - junit4
install:
  - sudo pip install codecov
script:
  - make clean
  - make compileTest
  - make runCov
  - make calCov
branches:
  only:
    - master
#after_success:
#  - codecov -X gcov
